/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user_interface;

/**
 *
 * @author 20168341
 */
public class FrontPage extends javax.swing.JFrame {
    
    /** Creates new form FrontPage */
    public FrontPage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        singlePlayerButton = new javax.swing.JPanel();
        singlePlayerText = new javax.swing.JLabel();
        versusButton = new javax.swing.JPanel();
        versusRed1 = new javax.swing.JLabel();
        versusVS = new javax.swing.JLabel();
        versusBlue1 = new javax.swing.JLabel();
        versusMode = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        settingsText = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frontPage"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/Antemies.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        singlePlayerButton.setBackground(new java.awt.Color(245, 245, 245));
        singlePlayerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        singlePlayerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        singlePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMousePressed(evt);
            }
        });

        singlePlayerText.setBackground(new java.awt.Color(245, 245, 245));
        singlePlayerText.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        singlePlayerText.setForeground(new java.awt.Color(102, 102, 102));
        singlePlayerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singlePlayerText.setText("Single player mode");
        singlePlayerText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout singlePlayerButtonLayout = new javax.swing.GroupLayout(singlePlayerButton);
        singlePlayerButton.setLayout(singlePlayerButtonLayout);
        singlePlayerButtonLayout.setHorizontalGroup(
            singlePlayerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singlePlayerButtonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(singlePlayerText)
                .addGap(30, 30, 30))
        );
        singlePlayerButtonLayout.setVerticalGroup(
            singlePlayerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singlePlayerButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(singlePlayerText)
                .addGap(10, 10, 10))
        );

        getContentPane().add(singlePlayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));

        versusButton.setBackground(new java.awt.Color(245, 245, 245));
        versusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        versusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        versusButton.setPreferredSize(new java.awt.Dimension(477, 84));
        versusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                versusButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                versusButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                versusButtonMousePressed(evt);
            }
        });

        versusRed1.setBackground(new java.awt.Color(245, 245, 245));
        versusRed1.setFont(new java.awt.Font("Lato", 1, 50)); // NOI18N
        versusRed1.setForeground(new java.awt.Color(211, 45, 43));
        versusRed1.setText("1");
        versusRed1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusVS.setBackground(new java.awt.Color(245, 245, 245));
        versusVS.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        versusVS.setForeground(new java.awt.Color(102, 102, 102));
        versusVS.setText("vs.");
        versusVS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusBlue1.setBackground(new java.awt.Color(245, 245, 245));
        versusBlue1.setFont(new java.awt.Font("Lato", 1, 50)); // NOI18N
        versusBlue1.setForeground(new java.awt.Color(30, 153, 224));
        versusBlue1.setText("1");
        versusBlue1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusMode.setBackground(new java.awt.Color(245, 245, 245));
        versusMode.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        versusMode.setForeground(new java.awt.Color(102, 102, 102));
        versusMode.setText("mode");
        versusMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout versusButtonLayout = new javax.swing.GroupLayout(versusButton);
        versusButton.setLayout(versusButtonLayout);
        versusButtonLayout.setHorizontalGroup(
            versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(versusButtonLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(versusRed1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusVS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusBlue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusMode)
                .addGap(103, 103, 103))
        );
        versusButtonLayout.setVerticalGroup(
            versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, versusButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versusBlue1)
                    .addComponent(versusVS)
                    .addComponent(versusMode)
                    .addComponent(versusRed1))
                .addGap(10, 10, 10))
        );

        getContentPane().add(versusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 547, -1, -1));

        settingsButton.setBackground(new java.awt.Color(245, 245, 245));
        settingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsButton.setPreferredSize(new java.awt.Dimension(477, 84));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsButtonMousePressed(evt);
            }
        });

        settingsText.setBackground(new java.awt.Color(245, 245, 245));
        settingsText.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        settingsText.setForeground(new java.awt.Color(102, 102, 102));
        settingsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/settingsIcon.png"))); // NOI18N
        settingsText.setText("Settings");
        settingsText.setIconTextGap(20);

        javax.swing.GroupLayout settingsButtonLayout = new javax.swing.GroupLayout(settingsButton);
        settingsButton.setLayout(settingsButtonLayout);
        settingsButtonLayout.setHorizontalGroup(
            settingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsButtonLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(settingsText)
                .addGap(113, 113, 113))
        );
        settingsButtonLayout.setVerticalGroup(
            settingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(settingsText)
                .addGap(10, 10, 10))
        );

        getContentPane().add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 681, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        SettingsPage settingsPage = new SettingsPage();
        settingsPage.setVisible(true);
        this.setVisible(false);
    }                                           

    private void singlePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        SinglePlayerPage singlePlayerPage = new SinglePlayerPage();
        singlePlayerPage.setVisible(true);
        this.setVisible(false);
    }                                               

    private void versusButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        VersusPage versusPage = new VersusPage();
        versusPage.setVisible(true);
        this.setVisible(false);
    }                                         

    private void singlePlayerButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                
        singlePlayerButton.setBackground(new java.awt.Color(234, 234, 234));
    }                                               

    private void singlePlayerButtonMouseExited(java.awt.event.MouseEvent evt) {                                               
        singlePlayerButton.setBackground(new java.awt.Color(245, 245, 245));
    }                                              

    private void singlePlayerButtonMousePressed(java.awt.event.MouseEvent evt) {                                                
        singlePlayerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }                                               

    private void versusButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        versusButton.setBackground(new java.awt.Color(234, 234, 234));
    }                                         

    private void versusButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        versusButton.setBackground(new java.awt.Color(245, 245, 245));
    }                                        

    private void versusButtonMousePressed(java.awt.event.MouseEvent evt) {                                          
        versusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }                                         

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
        settingsButton.setBackground(new java.awt.Color(234, 234, 234));
    }                                           

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
        settingsButton.setBackground(new java.awt.Color(245, 245, 245));
    }                                          

    private void settingsButtonMousePressed(java.awt.event.MouseEvent evt) {                                            
        settingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel background;
    private javax.swing.JPanel settingsButton;
    private javax.swing.JLabel settingsText;
    private javax.swing.JPanel singlePlayerButton;
    private javax.swing.JLabel singlePlayerText;
    private javax.swing.JLabel title;
    private javax.swing.JLabel versusBlue1;
    private javax.swing.JPanel versusButton;
    private javax.swing.JLabel versusMode;
    private javax.swing.JLabel versusRed1;
    private javax.swing.JLabel versusVS;
    // End of variables declaration                   
    
}
