/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user_interface;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JOptionPane;

/**
 *
 * @author 20168341
 */
public class PausePage extends javax.swing.JPanel {
	public int width;
	public int height;
	
	public volatile boolean close;
	public volatile boolean settings;
	public volatile boolean startGame;
	
    /** Creates new form FrontPage */
    public PausePage(int width, int height) {
    	this.width = width;
    	this.height = height;
    	
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        singlePlayerButton = new javax.swing.JPanel();
        singlePlayerText = new javax.swing.JLabel();
        versusButton = new javax.swing.JPanel();
        versusRed1 = new javax.swing.JLabel();
        versusVS = new javax.swing.JLabel();
        versusBlue1 = new javax.swing.JLabel();
        versusMode = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        settingsText = new javax.swing.JLabel();
        exitButton = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        
        //setUndecorated(true);
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("pausePage"); // NOI18N
        setSize(new java.awt.Dimension(width, height));
        //setSize(new java.awt.Dimension(1938, 1127));
        setLayout(null);
        //getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        /*addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                close = true;
            }
        });*/

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/Antemies.png"))); // NOI18N

        singlePlayerButton.setBackground(new java.awt.Color(245, 245, 245));
        singlePlayerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        singlePlayerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        singlePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                singlePlayerButtonMousePressed(evt);
            }
        });

        singlePlayerText.setBackground(new java.awt.Color(245, 245, 245));
        singlePlayerText.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        singlePlayerText.setForeground(new java.awt.Color(102, 102, 102));
        singlePlayerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singlePlayerText.setText("Resume");
        singlePlayerText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout singlePlayerButtonLayout = new javax.swing.GroupLayout(singlePlayerButton);
        singlePlayerButton.setLayout(singlePlayerButtonLayout);
        singlePlayerButtonLayout.setHorizontalGroup(
            singlePlayerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singlePlayerButtonLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(singlePlayerText)
                .addGap(140, 140, 140))
        );
        singlePlayerButtonLayout.setVerticalGroup(
            singlePlayerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singlePlayerButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(singlePlayerText)
                .addGap(10, 10, 10))
        );

        /*versusButton.setBackground(new java.awt.Color(245, 245, 245));
        versusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        versusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        versusButton.setPreferredSize(new java.awt.Dimension(477, 84));
        versusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                versusButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                versusButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                versusButtonMousePressed(evt);
            }
        });

        versusRed1.setBackground(new java.awt.Color(245, 245, 245));
        versusRed1.setFont(new java.awt.Font("Lato", 1, 50)); // NOI18N
        versusRed1.setForeground(new java.awt.Color(211, 45, 43));
        versusRed1.setText("1");
        versusRed1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusVS.setBackground(new java.awt.Color(245, 245, 245));
        versusVS.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        versusVS.setForeground(new java.awt.Color(102, 102, 102));
        versusVS.setText("vs.");
        versusVS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusBlue1.setBackground(new java.awt.Color(245, 245, 245));
        versusBlue1.setFont(new java.awt.Font("Lato", 1, 50)); // NOI18N
        versusBlue1.setForeground(new java.awt.Color(30, 153, 224));
        versusBlue1.setText("1");
        versusBlue1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        versusMode.setBackground(new java.awt.Color(245, 245, 245));
        versusMode.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        versusMode.setForeground(new java.awt.Color(102, 102, 102));
        versusMode.setText("mode");
        versusMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout versusButtonLayout = new javax.swing.GroupLayout(versusButton);
        versusButton.setLayout(versusButtonLayout);
        versusButtonLayout.setHorizontalGroup(
            versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(versusButtonLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(versusRed1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusVS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusBlue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versusMode)
                .addGap(103, 103, 103))
        );
        versusButtonLayout.setVerticalGroup(
            versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, versusButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(versusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versusBlue1)
                    .addComponent(versusVS)
                    .addComponent(versusMode)
                    .addComponent(versusRed1))
                .addGap(10, 10, 10))
        );*/

        //getContentPane().add(versusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 547, -1, -1));

        settingsButton.setBackground(new java.awt.Color(245, 245, 245));
        settingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsButton.setPreferredSize(new java.awt.Dimension(477, 84));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsButtonMousePressed(evt);
            }
        });

        settingsText.setBackground(new java.awt.Color(245, 245, 245));
        settingsText.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        settingsText.setForeground(new java.awt.Color(102, 102, 102));
        settingsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/settingsIcon.png"))); // NOI18N
        settingsText.setText("Settings");
        settingsText.setIconTextGap(20);

        javax.swing.GroupLayout settingsButtonLayout = new javax.swing.GroupLayout(settingsButton);
        settingsButton.setLayout(settingsButtonLayout);
        settingsButtonLayout.setHorizontalGroup(
            settingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsButtonLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(settingsText)
                .addGap(110, 110, 110))
        );
        settingsButtonLayout.setVerticalGroup(
            settingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(settingsText)
                .addGap(10, 10, 10))
        );

        exitButton.setBackground(new java.awt.Color(245, 245, 245));
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.setPreferredSize(new java.awt.Dimension(477, 84));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
        });

        exitText.setFont(new java.awt.Font("Lato", 0, 50)); // NOI18N
        exitText.setForeground(new java.awt.Color(102, 102, 102));
        exitText.setText("Exit");
        exitText.setIconTextGap(20);

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitButtonLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(exitText)
                .addGap(190, 190, 190))
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(exitText)
                .addGap(10, 10, 10))
        );
        
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/background.jpg"))); // NOI18N

        //title.setBounds(660, 150, 600, 160);
        title.setBounds((int) (width * 660f / 1920f), (int) (height * 150f / 1080f), (int) (width * 600f / 1920f), (int) (height * 160f / 1080f));
        add(title);
        //getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));
        
        //singlePlayerButton.setBounds(720, 500, 477, 90);
        singlePlayerButton.setBounds((int) (width * 720f / 1920f), (int) (height * 500f / 1080f), (int) (width * 477f / 1920f), (int) (height * 90f / 1080f));
        add(singlePlayerButton);
        //getContentPane().add(singlePlayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));
        
        //settingsButton.setBounds(720, 637, 477, 90);
        settingsButton.setBounds((int) (width * 720f / 1920f), (int) (height * 637f / 1080f), (int) (width * 477f / 1920f), (int) (height * 90f / 1080f));
        add(settingsButton);
        //getContentPane().add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 681, -1, -1));
        
        exitButton.setBounds(720, 774, 477, 90);
        exitButton.setBounds((int) (width * 720f / 1920f), (int) (height * 774f / 1080f), (int) (width * 477f / 1920f), (int) (height * 90f / 1080f));
        add(exitButton);

        background.setBounds(0, 0, width, height);
        add(background);
        //getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        //setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void singlePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
    	startGame = true;
    }       
    
    private void versusButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
    	
    }  
    
    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	settings = true;
    }
    
    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	close = true;
    }                                       

    private void singlePlayerButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                
        singlePlayerButton.setBackground(new java.awt.Color(31, 157, 228));
        singlePlayerText.setForeground(java.awt.Color.WHITE);
    }                                               

    private void singlePlayerButtonMouseExited(java.awt.event.MouseEvent evt) {                                               
        singlePlayerButton.setBackground(new java.awt.Color(245, 245, 245));
        singlePlayerText.setForeground(new java.awt.Color(102, 102, 102));
    }                                              

    private void singlePlayerButtonMousePressed(java.awt.event.MouseEvent evt) {                                                
        singlePlayerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }                                               

    private void versusButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        versusButton.setBackground(new java.awt.Color(234, 234, 234));
    }                                         

    private void versusButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        versusButton.setBackground(new java.awt.Color(245, 245, 245));
    }                                        

    private void versusButtonMousePressed(java.awt.event.MouseEvent evt) {                                          
        versusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }                                         

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
        settingsButton.setBackground(new java.awt.Color(31, 157, 228));
        settingsText.setForeground(java.awt.Color.WHITE);
    }                                           

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
        settingsButton.setBackground(new java.awt.Color(245, 245, 245));
        settingsText.setForeground(new java.awt.Color(102, 102, 102));
    }                                          

    private void settingsButtonMousePressed(java.awt.event.MouseEvent evt) {                                            
        settingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        settingsButton.setBackground(new java.awt.Color(245, 245, 245));
        settingsText.setForeground(new java.awt.Color(102, 102, 102));
    }
    
    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
        exitButton.setBackground(new java.awt.Color(215, 46, 44));
        exitText.setForeground(java.awt.Color.WHITE);
    }                                           

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
        exitButton.setBackground(new java.awt.Color(245, 245, 245));
        exitText.setForeground(new java.awt.Color(102, 102, 102));
    }                                          

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {                                            
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel background;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitText;
    private javax.swing.JPanel settingsButton;
    private javax.swing.JLabel settingsText;
    private javax.swing.JPanel singlePlayerButton;
    private javax.swing.JLabel singlePlayerText;
    private javax.swing.JLabel title;
    private javax.swing.JLabel versusBlue1;
    private javax.swing.JPanel versusButton;
    private javax.swing.JLabel versusMode;
    private javax.swing.JLabel versusRed1;
    private javax.swing.JLabel versusVS;
    // End of variables declaration                   
    
}
