/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.event.KeyEvent;

/**
 *
 * @author 20168341
 */
public class SettingsPage extends javax.swing.JPanel {
	public int width;
	public int height;
	
	public volatile boolean close;
    public volatile boolean frontPage;
    public volatile boolean volumeChange;
    public volatile boolean musicToggleON = true;
    public volatile boolean audioToggleON = true;

    /**
     * Creates new form SettingsPage
     */
    public SettingsPage(int width, int height) {
    	this.width = width;
    	this.height = height;
    	
        initComponents();
        musicValue.setText(String.valueOf(musicSlider.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        musicPanel = new javax.swing.JPanel();
        musicIcon = new javax.swing.JLabel();
        musicToggle = new javax.swing.JPanel();
        musicToggleText = new javax.swing.JLabel();
        musicSlider = new javax.swing.JSlider();
        musicValue = new javax.swing.JTextField();
        audioPanel = new javax.swing.JPanel();
        audioIcon = new javax.swing.JLabel();
        audioToggle = new javax.swing.JPanel();
        audioToggleText = new javax.swing.JLabel();
        audioSlider = new javax.swing.JSlider();
        audioValue = new javax.swing.JTextField();
        keyPanel = new javax.swing.JPanel();
        keyPanelIcon = new javax.swing.JPanel();
        keyboardIcon = new javax.swing.JLabel();
        keyboardText = new javax.swing.JLabel();
        wKey = new javax.swing.JPanel();
        wLetter = new javax.swing.JLabel();
        wDirection = new javax.swing.JLabel();
        sKey = new javax.swing.JPanel();
        sLetter = new javax.swing.JLabel();
        sDirection = new javax.swing.JLabel();
        aKey = new javax.swing.JPanel();
        aLetter = new javax.swing.JLabel();
        aDirection = new javax.swing.JLabel();
        dKey = new javax.swing.JPanel();
        dLetter = new javax.swing.JLabel();
        dDirection = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        //setUndecorated(true);
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frontPage"); // NOI18N
        setSize(new java.awt.Dimension(width, height));
        //setSize(new java.awt.Dimension(1938, 1127));
        setLayout(null);
        //getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(245, 245, 245));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/settingsTitle.png"))); // NOI18N

        backButton.setBackground(new java.awt.Color(245, 245, 245));
        backButton.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        backButton.setForeground(new java.awt.Color(102, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/backIcon.png"))); // NOI18N
        backButton.setText("Front page");
        backButton.setIconTextGap(10);
        backButton.setPreferredSize(new java.awt.Dimension(210, 37));
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });

        musicPanel.setBackground(new java.awt.Color(245, 245, 245));
        musicPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(153, 153, 153)));
        musicPanel.setPreferredSize(new java.awt.Dimension(600, 199));

        musicIcon.setFont(new java.awt.Font("Lato", 0, 40)); // NOI18N
        musicIcon.setForeground(new java.awt.Color(102, 102, 102));
        musicIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/musicIcon.png"))); // NOI18N
        musicIcon.setText("Music");
        musicIcon.setIconTextGap(10);
        musicIcon.setPreferredSize(new java.awt.Dimension(175, 63));

        musicToggle.setBackground(new java.awt.Color(30, 153, 224));
        musicToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        musicToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musicToggle.setPreferredSize(new java.awt.Dimension(120, 63));
        musicToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicToggleMouseClicked(evt);
            }
        });

        musicToggleText.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        musicToggleText.setForeground(new java.awt.Color(255, 255, 255));
        musicToggleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        musicToggleText.setText("ON");
        musicToggleText.setPreferredSize(new java.awt.Dimension(60, 40));

        javax.swing.GroupLayout musicToggleLayout = new javax.swing.GroupLayout(musicToggle);
        musicToggle.setLayout(musicToggleLayout);
        musicToggleLayout.setHorizontalGroup(
            musicToggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicToggleLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(musicToggleText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        musicToggleLayout.setVerticalGroup(
            musicToggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicToggleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(musicToggleText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        musicSlider.setToolTipText("");
        musicSlider.setPreferredSize(new java.awt.Dimension(200, 43));
        musicSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musicSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                musicSliderStateChanged(evt);
            }
        });

        musicValue.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        musicValue.setForeground(new java.awt.Color(102, 102, 102));
        musicValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        musicValue.setText("50");
        musicValue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        musicValue.setPreferredSize(new java.awt.Dimension(60, 43));
        musicValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                musicValueKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout musicPanelLayout = new javax.swing.GroupLayout(musicPanel);
        musicPanel.setLayout(musicPanelLayout);
        musicPanelLayout.setHorizontalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musicSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(musicPanelLayout.createSequentialGroup()
                        .addComponent(musicIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(musicToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(musicValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        musicPanelLayout.setVerticalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(musicValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(musicPanelLayout.createSequentialGroup()
                        .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musicToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(musicSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        audioPanel.setBackground(new java.awt.Color(245, 245, 245));
        audioPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(153, 153, 153)));
        audioPanel.setPreferredSize(new java.awt.Dimension(600, 199));

        audioIcon.setFont(new java.awt.Font("Lato", 0, 40)); // NOI18N
        audioIcon.setForeground(new java.awt.Color(102, 102, 102));
        audioIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/AudioIcon.png"))); // NOI18N
        audioIcon.setText("Audio");
        audioIcon.setIconTextGap(10);
        audioIcon.setPreferredSize(new java.awt.Dimension(173, 63));

        audioToggle.setBackground(new java.awt.Color(30, 153, 224));
        audioToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        audioToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        audioToggle.setPreferredSize(new java.awt.Dimension(120, 63));
        audioToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audioToggleMouseClicked(evt);
            }
        });

        audioToggleText.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        audioToggleText.setForeground(new java.awt.Color(255, 255, 255));
        audioToggleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        audioToggleText.setText("ON");
        audioToggleText.setPreferredSize(new java.awt.Dimension(60, 40));

        javax.swing.GroupLayout audioToggleLayout = new javax.swing.GroupLayout(audioToggle);
        audioToggle.setLayout(audioToggleLayout);
        audioToggleLayout.setHorizontalGroup(
            audioToggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioToggleLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(audioToggleText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        audioToggleLayout.setVerticalGroup(
            audioToggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioToggleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(audioToggleText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        audioSlider.setToolTipText("");
        audioSlider.setPreferredSize(new java.awt.Dimension(200, 43));
        audioSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                audioSliderStateChanged(evt);
            }
        });

        audioValue.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        audioValue.setForeground(new java.awt.Color(102, 102, 102));
        audioValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        audioValue.setText("50");
        audioValue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        audioValue.setPreferredSize(new java.awt.Dimension(60, 43));
        audioValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                audioValueKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout audioPanelLayout = new javax.swing.GroupLayout(audioPanel);
        audioPanel.setLayout(audioPanelLayout);
        audioPanelLayout.setHorizontalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(audioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(audioPanelLayout.createSequentialGroup()
                        .addComponent(audioIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(audioToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(audioValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        audioPanelLayout.setVerticalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(audioIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(audioValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(audioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        
        keyPanel.setBackground(new java.awt.Color(245, 245, 245));
        keyPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(153, 153, 153)));
        keyPanel.setPreferredSize(new java.awt.Dimension(600, 199));

        keyPanelIcon.setBackground(new java.awt.Color(245, 245, 245));

        keyboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/keyboardIcon.png"))); // NOI18N

        keyboardText.setFont(new java.awt.Font("Lato", 0, 40)); // NOI18N
        keyboardText.setForeground(new java.awt.Color(102, 102, 102));
        keyboardText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyboardText.setText("Keyboard");
        keyboardText.setIconTextGap(10);

        javax.swing.GroupLayout keyPanelIconLayout = new javax.swing.GroupLayout(keyPanelIcon);
        keyPanelIcon.setLayout(keyPanelIconLayout);
        keyPanelIconLayout.setHorizontalGroup(
            keyPanelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keyboardText)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyPanelIconLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keyboardIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        keyPanelIconLayout.setVerticalGroup(
            keyPanelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPanelIconLayout.createSequentialGroup()
                .addComponent(keyboardIcon)
                .addGap(0, 0, 0)
                .addComponent(keyboardText)
                .addGap(0, 0, 0))
        );

        wKey.setBackground(new java.awt.Color(245, 245, 245));

        wLetter.setBackground(new java.awt.Color(245, 245, 245));
        wLetter.setFont(new java.awt.Font("Lato", 1, 100)); // NOI18N
        wLetter.setForeground(new java.awt.Color(102, 102, 102));
        wLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wLetter.setText("W");
        wLetter.setIconTextGap(10);

        wDirection.setBackground(new java.awt.Color(245, 245, 245));
        wDirection.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        wDirection.setForeground(new java.awt.Color(102, 102, 102));
        wDirection.setText("Front");

        javax.swing.GroupLayout wKeyLayout = new javax.swing.GroupLayout(wKey);
        wKey.setLayout(wKeyLayout);
        wKeyLayout.setHorizontalGroup(
            wKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wKeyLayout.createSequentialGroup()
                .addGroup(wKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wLetter)
                    .addGroup(wKeyLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(wDirection)))
                .addGap(0, 0, 0))
        );
        wKeyLayout.setVerticalGroup(
            wKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wKeyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(wLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wDirection)
                .addGap(0, 0, 0))
        );

        aKey.setBackground(new java.awt.Color(245, 245, 245));
        aKey.setPreferredSize(new java.awt.Dimension(108, 146));

        aLetter.setBackground(new java.awt.Color(245, 245, 245));
        aLetter.setFont(new java.awt.Font("Lato", 1, 100)); // NOI18N
        aLetter.setForeground(new java.awt.Color(102, 102, 102));
        aLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLetter.setText("A");
        aLetter.setIconTextGap(10);

        aDirection.setBackground(new java.awt.Color(245, 245, 245));
        aDirection.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        aDirection.setForeground(new java.awt.Color(102, 102, 102));
        aDirection.setText("Left");

        javax.swing.GroupLayout aKeyLayout = new javax.swing.GroupLayout(aKey);
        aKey.setLayout(aKeyLayout);
        aKeyLayout.setHorizontalGroup(
            aKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aKeyLayout.createSequentialGroup()
                .addGroup(aKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aKeyLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(aDirection)))
                .addGap(0, 0, 0))
        );
        aKeyLayout.setVerticalGroup(
            aKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aKeyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(aLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(aDirection)
                .addGap(0, 0, 0))
        );

        sKey.setBackground(new java.awt.Color(245, 245, 245));
        sKey.setPreferredSize(new java.awt.Dimension(108, 146));

        sLetter.setBackground(new java.awt.Color(245, 245, 245));
        sLetter.setFont(new java.awt.Font("Lato", 1, 100)); // NOI18N
        sLetter.setForeground(new java.awt.Color(102, 102, 102));
        sLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLetter.setText("S");
        sLetter.setIconTextGap(10);

        sDirection.setBackground(new java.awt.Color(245, 245, 245));
        sDirection.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        sDirection.setForeground(new java.awt.Color(102, 102, 102));
        sDirection.setText("Back");

        javax.swing.GroupLayout sKeyLayout = new javax.swing.GroupLayout(sKey);
        sKey.setLayout(sKeyLayout);
        sKeyLayout.setHorizontalGroup(
            sKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sKeyLayout.createSequentialGroup()
                .addGroup(sKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sKeyLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sDirection)))
                .addGap(0, 0, 0))
        );
        
        sKeyLayout.setVerticalGroup(
            sKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sKeyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sDirection)
                .addGap(0, 0, 0))
        );
        
        dKey.setBackground(new java.awt.Color(245, 245, 245));
        dKey.setPreferredSize(new java.awt.Dimension(108, 146));

        dLetter.setBackground(new java.awt.Color(245, 245, 245));
        dLetter.setFont(new java.awt.Font("Lato", 1, 100)); // NOI18N
        dLetter.setForeground(new java.awt.Color(102, 102, 102));
        dLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dLetter.setText("D");
        dLetter.setIconTextGap(10);

        dDirection.setBackground(new java.awt.Color(245, 245, 245));
        dDirection.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        dDirection.setForeground(new java.awt.Color(102, 102, 102));
        dDirection.setText("Right");

        javax.swing.GroupLayout dKeyLayout = new javax.swing.GroupLayout(dKey);
        dKey.setLayout(dKeyLayout);
        dKeyLayout.setHorizontalGroup(
            dKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dKeyLayout.createSequentialGroup()
                .addGroup(dKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dKeyLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(dDirection)))
                .addGap(0, 0, 0))
        );
        dKeyLayout.setVerticalGroup(
            dKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dKeyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(dLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dDirection)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout keyPanelLayout = new javax.swing.GroupLayout(keyPanel);
        keyPanel.setLayout(keyPanelLayout);
        keyPanelLayout.setHorizontalGroup(
            keyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(keyPanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(wKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(sKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        keyPanelLayout.setVerticalGroup(
            keyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(keyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(keyPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(keyPanelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/images/background.jpg"))); // NOI18N
       
        //title.setBounds(760, 100, title.getPreferredSize().width, 160);
        title.setBounds((int) (width * 760f / 1920f), (int) (height * 100f / 1080f), (int) (width * 600f / 1920f), (int) (height * 160f / 1080f));
        add(title);
        //getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));
        
        //backButton.setBounds(50, 50, backButton.getPreferredSize().width, backButton.getPreferredSize().height);
        backButton.setBounds((int) (width * 50f / 1920f), (int) (height * 50f / 1080f), (int) (width * (float) backButton.getPreferredSize().width / 1920f), (int) (height * (float) backButton.getPreferredSize().height / 1080f));
        add(backButton);
        //getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        
        //musicPanel.setBounds(310, 307, musicPanel.getPreferredSize().width, musicPanel.getPreferredSize().height);
        musicPanel.setBounds((int) (width * 660f / 1920f), (int) (height * 400f / 1080f), (int) (width * (float) musicPanel.getPreferredSize().width / 1920f), (int) (height * (float) musicPanel.getPreferredSize().height / 1080f));
        add(musicPanel);
        //getContentPane().add(musicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 307, -1, -1));
        
        //audioPanel.setBounds(1010, 307, audioPanel.getPreferredSize().width, audioPanel.getPreferredSize().height);
        //musicPanel.setBounds((int) (width * 1010f / 1920f), (int) (height * 307f / 1080f), (int) (width * (float) audioPanel.getPreferredSize().width / 1920f), (int) (height * (float) audioPanel.getPreferredSize().height / 1080f));
        //add(audioPanel);
        //getContentPane().add(audioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 307, -1, -1));

        //keyPanel.setBounds(310, 606, 1300, 189);
        keyPanel.setBounds((int) (width * 310f / 1920f), (int) (height * 700f / 1080f), (int) (width * 1300f / 1920f), (int) (height * 189f / 1080f));
        add(keyPanel);
        //getContentPane().add(keyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 606, 1300, 189));
        
        background.setBounds(0, 0, width, height);
        add(background);
        //getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
        
        //setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        frontPage = true;
    }                                       

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {                                        
        backButton.setFont(new java.awt.Font("Lato", 0, 34));
    }                                       

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {                                       
        backButton.setFont(new java.awt.Font("Lato", 0, 30));
    }                                      

    private void musicToggleMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (musicToggleON) {
            musicToggle.setBackground(new java.awt.Color(211, 45, 43));
            musicToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            musicToggleText.setText("OFF");
            musicToggleON = false;
        } else {
            musicToggle.setBackground(new java.awt.Color(30, 153, 224));
            musicToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            musicToggleText.setText("ON");
            musicToggleON = true;
        }
    }                                        

    private void audioToggleMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (audioToggleON) {
            audioToggle.setBackground(new java.awt.Color(211, 45, 43));
            audioToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            audioToggleText.setText("OFF");
            audioToggleON = false;
        } else {
            audioToggle.setBackground(new java.awt.Color(30, 153, 224));
            audioToggle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            audioToggleText.setText("ON");
            audioToggleON = true;
        }    }                                        

    private void musicSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                         
        musicValue.setText(String.valueOf(musicSlider.getValue()));
        volumeChange = true;
    }                                        

    private void audioSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                         
        audioValue.setText(String.valueOf(audioSlider.getValue()));
    }                                        

    private void musicValueKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            musicSlider.setValue(Integer.parseInt(musicValue.getText()));
        }
    }                                     

    private void audioValueKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            audioSlider.setValue(Integer.parseInt(audioValue.getText()));
        }
    }
    
    public int getVolume() {
    	return musicSlider.getValue();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel aDirection;
    private javax.swing.JPanel aKey;
    private javax.swing.JLabel aLetter;
    private javax.swing.JLabel audioIcon;
    private javax.swing.JPanel audioPanel;
    private javax.swing.JSlider audioSlider;
    private javax.swing.JPanel audioToggle;
    private javax.swing.JLabel audioToggleText;
    private javax.swing.JTextField audioValue;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel dDirection;
    private javax.swing.JPanel dKey;
    private javax.swing.JLabel dLetter;
    private javax.swing.JPanel keyPanel;
    private javax.swing.JPanel keyPanelIcon;
    private javax.swing.JLabel keyboardIcon;
    private javax.swing.JLabel keyboardText;
    private javax.swing.JLabel musicIcon;
    private javax.swing.JPanel musicPanel;
    private javax.swing.JSlider musicSlider;
    private javax.swing.JPanel musicToggle;
    private javax.swing.JLabel musicToggleText;
    private javax.swing.JTextField musicValue;
    private javax.swing.JLabel sDirection;
    private javax.swing.JPanel sKey;
    private javax.swing.JLabel sLetter;
    private javax.swing.JLabel title;
    private javax.swing.JLabel wDirection;
    private javax.swing.JPanel wKey;
    private javax.swing.JLabel wLetter;
    // End of variables declaration                   
}
